### ISSUE TITLE
Rebuild require textfield.gadget

### ISSUE THREAD

**Issue by tomsmart1** [dmcoles/ReBuild#2]
textfield.gadget is need to start Rebuild  but AmigaOs 3.2.x does not provide it so a copy form ClassAct distribution is needed.

**Comment by dmcoles** [comment]
Thanks I'll take a look at this and update to make it optional

**Comment by dmcoles** [comment]
fixed in 0.3.0-alpha

**Comment by jman-schief** [comment]
hello @dmcoles now ReBuild does not need the textfield.gadget anymore. I was curious what actually changed in the capabilities of Rebuild. Does the lack of this library (meant to create areas for text entry) precludes some kind of code building? 

If this library is optional but *could* actually be a useful addition to create code with ReBuild, maybe a mention in the documentation somewhere could be nice.

thanks

**Comment by dmcoles** [comment]
If you try to add a textfield gadget without the relevant library installed you will just see a box with a cross in it on the preview. This doesn't affect the functionality of the software other than you cannot see what it looks like in the preview. If you generate code from that design the code will be exactly the same as it would be if you had the library installed but the code will not run correctly as it will expect that library to be present.
