### ISSUE TITLE
Rebuild 0.2.0 made many (Enforcer/MUForce) Hits at startup 

### ISSUE THREAD

**Issue by tomsmart1** [dmcoles/ReBuild#3]
Here the start Hit recorded at  REbuild 0.2.0 startup from AOS 3.2.2.1 

`.
19-Nov-23   16:04:13..
LONG READ from 00000000                        PC: 0FFC994E.
USP : 0972E6A0 SR: 0000  (U0)(-)(-)  TCB: 097BA7B0.
Data: 00000001 FFFFE801 00000006 080121D8 097F3648 0000001D 09736218 00000000.
Addr: 09736218 0800C926 00000000 09736218 0972ED10 00000000 0800C104 08954570.
Stck: 0000E801 0972E700 0800C104 0800E801 0000E801 0800C104 0FFCAFAC FFFFFFFF.
Stck: 097BA352 097361F6 0800C104 097B12B4 080121D8 097F3648 00000006 00000004.
Stck: 00000003 0800C104 0FFC0092 00000000 097BA352 00000000 0800C104 00000000.
Stck: 0972E720 097B0AA0 00000000 096A55DE 09730C54 097292D8 00000003 00000000.
Stck: 0972E79C 097B54C8 00000000 00000014 097B6F62 00000000 00000000 00000000.
Stck: 080121D8 096A55DE 09730C54 097292D8 00000014 00000000 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 FFFFFFFF.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 09751434 0974F4BF.
Stck: 097AF6A0 00000000 00C8002B 52654275 696C6420 2D205265 61637469 6F6E2055.
Stck: 49204275 696C6465 72202830 2E322E30 2D616C70 68612900 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00FF0000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000.
Stck: 0971B0F4 097E5ABC 097E645C 097E6984 097E7324 097E7CC4 097433DC 09730CFC.
Stck: 097310C4 0973148C 09731E94 09734D74 097351F4 0973700C 097374FC 09737F74.
Stck: 0973A4A4 0973A67C 0001097B 80D60000 0000FFFF FFFFFFFF FFFFFFFF 0008097B.
Stck: 85560000 00000003 097B8551 00000000 0002097B 854E0000 0000FFFF FFFFFFFF.
Stck: FFFFFFFF 0974F430 097EA764 0972E980 09718368 09727248 09727254 09717FD8.
Stck: 09735F1C 0971AC80 097287AC 097E81EC 0972E880 0972E9C8 00000000 0972E7AC.
Stck: 097430EC 00000000 00000000 0972E9DC 00000006 096AF818 09702540 00000000.
Stck: 09713450 00000000 00000000 09718190 00000000 00000000 09718528 09727260.
Stck: 00000000 00000000 08C592E0 096CDE48 096C6F10 096C3AE8 097174F4 09713168.
Stck: 09707510 097009F0 096D7CE0 096D25C4 096D19C8 096AF058 096CAE48 096B0218.
Stck: 096DE4F8 096D2220 096F8F40 096EAF4C 09717960 09708300 096AE748 096D2E30.
Stck: 09700898 096D0928 096D4EC0 097070D0 096C36E0 096C6C08 097023C8 096EB294.
Stck: 096DE860 096ADF0C 096B7E58 096A91EC 00000000 00000000 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000.
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 097BA7B0 00000000.
Stck: 00000000 00000000 0000126C 09727364 00000000 00000000 0972E79C 00000000.
Stck: 0972E734 097B760C 00000000 00000000 097292D8 00000000 00000000 08004FC8.
Stck: 0800C104 080121D8 08000884 096A55DE 0974F4BF 00000000 0974F430 097F2F28.
Stck: 00000000 00000000 00000000 0972EA08 00000000 0972EE88 0972EEB4 0972EEE8.
Stck: 0972EF60 0972EF94 0972F00C 0972F03C 0972F0B4 0972F0E4 0972F15C 0972F18C.
Stck: 0972F204 0972F234 0972F2AC 0972F2DC 0972F354 0972F384 0972F404 0972F444.
Stck: 0972F4BC 0972F4F0 0972F568 0972F598 0972F610 0972F644 0972F6BC 0972F6F0.
Stck: 0972F710 0972F788 0972F7B4 0972F7F8 0972F828 0972F8A0 0972F8D0 0972F948.
Stck: 0972F978 0972F9F0 0972FA24 0972FA9C 0972FAD0 0972FB48 0972FB7C 0972FBF4.
Stck: 0972FC6C 0972FC9C 0972FD14 0972FD44 0972FDBC 0972FDEC 0972FE64 0972FE94.
Stck: 0972FF0C 0972FF3C 0972FFB4 0972FFE8 09730014 09730040 097300B8 09730130.
Stck: 09730160 09730198 09730210 0973025C 097302D8 0973030C 09730388 097303BC.
Stck: 09730438 0973046C 097304E8 09730524 0973054C 097305C4 097305F8 09730670.
Stck: 097306A0 09730718 0973074C 097307C4 097307F8 09730870 097308A0 09730918.
Stck: 09730948 097309C0 097309F0 09730A20 09730A74 09730AA0 09730B04 09730B78.
Stck: 09730BE8 09730C18 00000018 0979E3C6 0979E3B6 0979E3AC 0979E3A2 0979E374.
----> 0FFC994E - "LDM - intuition 47.52 (19.4.2022)"  Hunk 0000 Offset 0000A926.
----> 0FFCAFAC - "LDM - intuition 47.52 (19.4.2022)"  Hunk 0000 Offset 0000BF84.
----> 097BA352 - "AMIDEV:Test/Rebuild/rebuild"  Hunk 0000 Offset 0006B032.
----> 097B12B4 - "AMIDEV:Test/Rebuild/rebuild"  Hunk 0000 Offset 00061F94.
----> 0FFC0092 - "LDM - intuition 47.52 (19.4.2022)"  Hunk 0000 Offset 0000106A.
----> 097BA352 - "AMIDEV:Test/Rebuild/rebuild"  Hunk 0000 Offset 0006B032.
----> 097B0AA0 - "AMIDEV:Test/Rebuild/rebuild"  Hunk 0000 Offset 00061780.
----> 097B54C8 - "AMIDEV:Test/Rebuild/rebuild"  Hunk 0000 Offset 000661A8.
----> 097B6F62 - "AMIDEV:Test/Rebuild/rebuild"  Hunk 0000 Offset 00067C42.
----> 09751434 - "AMIDEV:Test/Rebuild/rebuild"  Hunk 0000 Offset 00002114.
----> 0974F4BF - "AMIDEV:Test/Rebuild/rebuild"  Hunk 0000 Offset 0000019F.
----> 097AF6A0 - "AMIDEV:Test/Rebuild/rebuild"  Hunk 0000 Offset 00060380.
----> 00FF0000 - "ROM - wb 40.5 (24.5.93)"  Hunk 0000 Offset 00002954.
----> 097B80D6 - "AMIDEV:Test/Rebuild/rebuild"  Hunk 0000 Offset 00068DB6.
----> 097B8556 - "AMIDEV:Test/Rebuild/rebuild"  Hunk 0000 Offset 00069236.
----> 097B8551 - "AMIDEV:Test/Rebuild/rebuild"  Hunk 0000 Offset 00069231.
----> 097B854E - "AMIDEV:Test/Rebuild/rebuild"  Hunk 0000 Offset 0006922E.
----> 0974F430 - "AMIDEV:Test/Rebuild/rebuild"  Hunk 0000 Offset 00000110.
----> 097B760C - "AMIDEV:Test/Rebuild/rebuild"  Hunk 0000 Offset 000682EC.
----> 0974F4BF - "AMIDEV:Test/Rebuild/rebuild"  Hunk 0000 Offset 0000019F.
----> 0974F430 - "AMIDEV:Test/Rebuild/rebuild"  Hunk 0000 Offset 00000110.
----> 09180973 - "THD2:Libs/expat.library"  Hunk 0000 Offset 00001D83.
----> 0979E3C6 - "AMIDEV:Test/Rebuild/rebuild"  Hunk 0000 Offset 0004F0A6.
----> 0979E3B6 - "AMIDEV:Test/Rebuild/rebuild"  Hunk 0000 Offset 0004F096.
----> 0979E3AC - "AMIDEV:Test/Rebuild/rebuild"  Hunk 0000 Offset 0004F08C.
----> 0979E3A2 - "AMIDEV:Test/Rebuild/rebuild"  Hunk 0000 Offset 0004F082.
----> 0979E374 - "AMIDEV:Test/Rebuild/rebuild"  Hunk 0000 Offset 0004F054.
PC-8: 000EE040 E6403E00 0247001F 2F4E0014 701FBE40 66047000 60122C6F 00140C40.
PC *: 2A552007 53474A40 6EF6200D 4CDF6080 DEFC000C 4E75594F 48E70006 2A4E2F4E.
0ffc994e : *2a55                       movea.l (a5),a5.
0ffc9950 :  2007                       move.l d7,d0.
0ffc9952 :  5347                       subq.w #$1,d7.
0ffc9954 :  4a40                       tst.w d0.
0ffc9956 :  6ef6                       bgt.s $ffc994e.
0ffc9958 :  200d                       move.l a5,d0.
0ffc995a :  4cdf 6080                  movem.l (a7)+,d7/a5-a6.
0ffc995e :  defc 000c                  adda.w #$c,a7.
0ffc9962 :  4e75                       rts.
0ffc9964 :  594f                       subq.w #$4,a7.
0ffc9966 :  48e7 0006                  movem.l a5-a6,-(a7).
0ffc996a :  2a4e                       movea.l a6,a5.
0ffc996c :  2f4e 0008                  move.l a6,$8(a7).
Name: "Rebuild"  .
.
.....
.`

Rest in the attached file.
[Rebuild_startup_hits.txt](https://github.com/dmcoles/ReBuild/files/13403604/Rebuild_startup_hits.txt)

**Comment by dmcoles** [comment]
Thanks. I believe this has already been fixed. It will be available I the 0.3.0 release

**Comment by dmcoles** [comment]
fixed in 0.3.0-alpha
