### ISSUE TITLE
Hide not available gadgets

### ISSUE THREAD

**Issue by walkero-gr** [dmcoles/ReBuild#7]
You have a window that shows gadgets that are available and their version. I am not sure the window to add them takes that in consideration.

I would like to suggest that those that are missing to not show them as available to be added, or ghost their button. Otherwise, someone might click on them and have the app crashing.

**Comment by dmcoles** [comment]
Rebuild is designed to be used for building reaction applications under OS3.2. When used in this way v ago the gadgets will be available for use.

If used under older versions of reaction or with classact then some gadgets will not display in the preview. Instead you will see a placeholder image. The application will still function fully in every other way. You will still be able to create designs using those gadgets and configure their settings. You can also still generate the code (which will be able to be used on a machine with the necessary gadgets installed).

Disabling the gadgets that don't exist on your machine would limit the application unnecessarily and would not prevent you from loading an existing project file containing these gadgets.

I'm struggling to see the benefit of doing what you are describing.

**Comment by walkero-gr** [comment]
If ReBuild does not crash when adding missing gadgets, then this is fine, with showing the placeholder. I am just thinking how this can be prevented.

You are welcome to close this issue if you do not see any benefit of it.
